version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remote_architects_club
    # environment:
    #   - APPLICATION_PORT=3310
    #   - DATABASE_URL=
    #   - DATABASE_SCHEMA=public
    #   - DATABASE_SSL=true
    #   - FOREST_AUTH_SECRET=
    #   - FOREST_ENV_SECRET=
    ports:
      - "3310:3310"
    volumes:
      - ./:/usr/src/app
