// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const CategoryTool = sequelize.define('categoryTool', {
    name: {
      type: DataTypes.STRING,
      primaryKey: true,
    },
    comment: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'category_tool',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  CategoryTool.associate = (models) => {
    CategoryTool.belongsToMany(models.tool, {
      through: 'tool_category',
      foreignKey: 'category_name',
      otherKey: 'tool_id',
    });
  };

  return CategoryTool;
};
