// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const OfficeTool = sequelize.define('officeTool', {
  }, {
    tableName: 'office_tool',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });
  OfficeTool.removeAttribute('id');
  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  OfficeTool.associate = (models) => {
    OfficeTool.belongsTo(models.office, {
      foreignKey: {
        name: 'officeIdKey',
        field: 'office_id',
      },
      as: 'office',
    });
    OfficeTool.belongsTo(models.tool, {
      foreignKey: {
        name: 'toolIdKey',
        field: 'tool_id',
      },
      as: 'tool',
    });
  };

  return OfficeTool;
};
